### ISSUE TITLE
No error information is displayed after parse error from assert

### ISSUE THREAD

**Issue by mbeckerle** [apache/daffodil-vscode#648]
Trying to test the vscode extension with the PCAP DFDL schema.

I clobbered the magic number in the first bytes of an icmp1.cap file. This fails an assert at line 97 of pcap.dfdl.xsd, which is the first element of simple type in the schema. 

I step through with the debugger, and nothing displays *anything* about the assert failure. Execution ends. A little pop-up dialog says it wrote my infoset out, which it didn't. There's nothing showing that anything went wrong. All panels on the left are blank.

I was testing 1.3.0-RC2 version of the vscode extension.

**Comment by mbeckerle** [comment]
I created an icmp1.bad.cap where I hammered the first byte to be 0x00. Using that as the data file causes the failure.

**Comment by shanedell** [comment]
@mbeckerle Thank you for this information this helped me reproduce the issue! I will get working on a fix, thank you again

**Comment by mbeckerle** [comment]
Testing 1.3.0-RC3

You got this output, which would be great:
```java.lang.Error: Parse Error: Assertion failed: Magic number was not 0xA1B2C3D4 (for bigEndian) or 0xD4C3B2A1 (for littleEndian).
Schema context: MagicNumber Location line 87 column 14 in file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd
Data location was preceding byte 4
```
Alas, my debug console window is empty, and the terminal window does not contain the characters "assert" (case insensitive). So I am simply not getting anything to indicate an error occurred.

**Comment by shanedell** [comment]
@mbeckerle are you on the terminal tab? By default I think it ends and goes to console or debug console but those won't have the output. There should a tab called Terminal that you can click on and see all the information from the debugger

**Comment by mbeckerle** [comment]
I am testing 1.3.0-RC3.

Complete output from terminal is attached in a file. Note there is a backtrace. 
[terminal-output.zip](https://github.com/apache/daffodil-vscode/files/11826857/terminal-output.zip)

**Comment by shanedell** [comment]
@mbeckerle can you try removing this folder: /home/mbeckerle/.local/share/daffodil-dap/ and run the debug again? I believe you are using an old version of the debugger and that is why you are not seeing the output you should.

**Comment by shanedell** [comment]
@mbeckerle If the above comment fixes the issue, we have another GitHub issue about making testing local changes to the debugger easier. If this is the issue you see I think it would be in the best interest to figure out another way of extracting the debugger or bundling the debugger so that you always use the latest and won't hit this issue anymore

**Comment by mbeckerle** [comment]
Uninstalling the debugger should delete ~/.local/share/daffodil-dap if it installs it there. 

I do indeed get an assert-related error to the terminal now. But then a big noisy backtrace due to exception in initializer error. 

Can we turn down the Logging level from INFO to remove some of the noise from the terminal?

```
java.lang.Error: Parse Error: Assertion failed: Magic number was not 0xA1B2C3D4 (for bigEndian) or 0xD4C3B2A1 (for littleEndian).
Schema context: MagicNumber Location line 87 column 14 in file:/home/mbeckerle/dataiti/opensource/DFDLSchemas/PCAP/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd
Data location was preceding byte 4
        at org.apache.daffodil.debugger.dap.Parse$$anon$1.$anonfun$run$2(Parse.scala:113)
        at as @ com.monovore.decline.effect.CommandIOApp$.addVersionFlag(CommandIOApp.scala:67)
2023-06-22 16:54:18,313 [io-compute-3] INFO  o.a.d.d.d.DAPSession - R> #16 disconnect {"restart":false} 
2023-06-22 16:54:18,315 [io-compute-7] INFO  o.a.d.d.d.DAPSession - <R #16 disconnect success null 
2023-06-22 16:54:18,316 [io-compute-blocker-5] DEBUG o.a.d.d.d.DAPodil - launched: Succeeded 
2023-06-22 16:54:18,316 [io-compute-blocker-5] DEBUG o.a.d.d.d.Parse - signalling a stop 
2023-06-22 16:54:18,317 [io-compute-blocker-5] DEBUG o.a.d.d.d.Parse - parse done, no interruption 
Exception in thread "io-compute-6" java.lang.ExceptionInInitializerError
        at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:81)
        at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:179)
        at com.sun.xml.bind.v2.runtime.reflect.Accessor$FieldReflection.optimize(Accessor.java:285)
        at com.sun.xml.bind.v2.runtime.property.ArrayProperty.<init>(ArrayProperty.java:68)
        at com.sun.xml.bind.v2.runtime.property.ArrayERProperty.<init>(ArrayERProperty.java:88)
        at com.sun.xml.bind.v2.runtime.property.ArrayElementProperty.<init>(ArrayElementProperty.java:100)
        at com.sun.xml.bind.v2.runtime.property.ArrayElementNodeProperty.<init>(ArrayElementNodeProperty.java:62)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:128)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:181)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:503)
   ...
```

**Comment by mbeckerle** [comment]
The back trace is a Java 17 issue. If I use Java 11 I do not get this backtrace.

**Comment by mbeckerle** [comment]
With a caveat that 1.3.0-RC3 still doesn't work with Java 17 (release note), this issue can be closed.

**Comment by arosien** [comment]
While this fix adds the error to the (terminal) console, we could also handle it by writing it to the "debug console":
<img width="1432" alt="Screen Shot 2023-07-10 at 2 05 21 PM" src="https://github.com/apache/daffodil-vscode/assets/31163/c91eab8b-0359-4736-8e3a-c427c4262b49">

or we could create a special event that causes a dialog/popup, like the current behavior when there is a compilation error in the schema.

What do you think @mbeckerle @shanedell?

**Comment by arosien** [comment]
I also saw the comments in #666 about feedback mechanisms. Instead of ending the debug session, we could raise an exception which would pause the debugger and the UI would show the assertion failure. Any subsequent "next" action would end the parse.

In contrast the current mechanism sends the error info, which we then log or show a dialog, but the debug session ends concurrently.

**Comment by shanedell** [comment]
@arosien I like displaying it in the "Debug Console". I wouldn't do the pop up or dialog because we had that before and it was removed  as @mbeckerle said it didn't need to be a blocking dialog
