### ISSUE TITLE
Blocking dialog displays schema definition errors

### ISSUE THREAD

**Issue by mbeckerle** [apache/daffodil-vscode#649]
If I modify my schema and make any mistake, then I get a blocking dialog showing the SDEs. 

This is basically intolerable, because you must dismiss it, and thereby lose the information you need from it, in order to look back at the schema to try to fix it. 

Back when the vscode extension was only a debugger this may have been more tolerable, because it was assumed that one would author the schema elsewhere. But now with the intellisense features coming along, one wants to author/edit the schema in the vscode extension also. So it needs to support editing the schema, getting SDEs, stepping through the SDEs so you can fix them. Try again, etc. until it is runnable. And then run in the debugger. 

The bare minimum fix would be to output the SDEs to a terminal window, or other persisting window that one can scroll back and forth in. Anything non-blocking really. 

You must be able to move through the SDEs as you move the editor to fix the schema. 

 I tested this on 1.3.0-RC2 of the vscode extension

**Comment by shanedell** [comment]
@mbeckerle Could you give the specific instance you found this happening just to help me reproduce?

**Comment by mbeckerle** [comment]
I was working with PCAP and ethernetIP schemas. 

Working with any schema at all I think should reproduce this however. 

E.g., just modify the representation="text" or represenatation="binary" and put a typo in the property name or value name.

**Comment by shanedell** [comment]
So @mbeckerle I believe it does output to the terminal already as I changed a property from `name` to `name1` and got that blocking dialog but the terminal also had the below content:

```bash
...
2023-06-14 18:34:37,692 [io-compute-9] DEBUG o.a.d.d.d.DAPodil - debugee: Errored(org.apache.daffodil.debugger.dap.Compiler$CompilationFailed: Schema Definition Error: Error loading schema due to org.xml.sax.SAXParseException; lineNumber: 93; columnNumber: 32; cvc-complex-type.3.2.2: Attribute 'name1' is not allowed to appear in element 'xs:element'.
Schema context: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd Location in file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd, Schema Definition Error: Error loading schema due to org.xml.sax.SAXParseException; systemId: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd; lineNumber: 93; columnNumber: 32; cvc-complex-type.3.2.2: Attribute 'name1' is not allowed to appear in element 'xs:element'.
Schema context: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd Location in file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd, Schema Definition Error: Error loading schema due to org.xml.sax.SAXParseException; systemId: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd; lineNumber: 93; columnNumber: 32; cvc-complex-type.3.2.2: Attribute 'name1' is not allowed to appear in element 'xs:element'.
Schema context: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd Location in file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd, Schema Definition Error: Error loading schema due to org.xml.sax.SAXParseException; systemId: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd; lineNumber: 93; columnNumber: 32; s4s-att-not-allowed: Attribute 'name1' cannot appear in element 'element'.
Schema context: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd Location in file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd, Schema Definition Error: Error loading schema due to org.xml.sax.SAXParseException; systemId: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd; lineNumber: 93; columnNumber: 32; src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
Schema context: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd Location in file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd) 
2023-06-14 18:34:37,695 [io-compute-9] WARN  o.a.d.d.d.DAPodil - couldn't launch, request #2 launch {"type":"dfdl","request":"launch","name":"pcap on icmp1.cap classpath with ethernetIP directory","program":"/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd","stopOnEntry":true,"data":"/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/test/resources/com/tresys/pcap/data/icmp1.bad.cap","infosetOutput":{"type":"file","path":"/tmp/pcap-icmp1.infoset.xml"},"debugServer":4711,"openHexView":false,"openInfosetView":false,"openInfosetDiffView":false,"useExistingServer":false,"daffodilDebugClasspath":"/Users/sdell/apache/sampleWorkspace/dfdl-ethernet/src/main/resources:/Users/sdell/apache/sampleWorkspace/dfdl-ethernet/target/classes","__configurationTarget":6,"__sessionId":"b4461f0e-618e-43a4-a5bb-2561031d89a7"} 
org.apache.daffodil.debugger.dap.Compiler$CompilationFailed: Schema Definition Error: Error loading schema due to org.xml.sax.SAXParseException; lineNumber: 93; columnNumber: 32; cvc-complex-type.3.2.2: Attribute 'name1' is not allowed to appear in element 'xs:element'.
Schema context: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd Location in file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd, Schema Definition Error: Error loading schema due to org.xml.sax.SAXParseException; systemId: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd; lineNumber: 93; columnNumber: 32; cvc-complex-type.3.2.2: Attribute 'name1' is not allowed to appear in element 'xs:element'.
Schema context: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd Location in file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd, Schema Definition Error: Error loading schema due to org.xml.sax.SAXParseException; systemId: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd; lineNumber: 93; columnNumber: 32; cvc-complex-type.3.2.2: Attribute 'name1' is not allowed to appear in element 'xs:element'.
Schema context: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd Location in file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd, Schema Definition Error: Error loading schema due to org.xml.sax.SAXParseException; systemId: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd; lineNumber: 93; columnNumber: 32; s4s-att-not-allowed: Attribute 'name1' cannot appear in element 'element'.
Schema context: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd Location in file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd, Schema Definition Error: Error loading schema due to org.xml.sax.SAXParseException; systemId: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd; lineNumber: 93; columnNumber: 32; src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
Schema context: file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd Location in file:/Users/sdell/apache/sampleWorkspace/dfdl-pcap/src/main/resources/com/tresys/pcap/xsd/pcap.dfdl.xsd
        at org.apache.daffodil.debugger.dap.Compiler$$anon$1.$anonfun$compile$2(Compiler.scala:38)
        at cats.MonadError.$anonfun$ensureOr$1(MonadError.scala:41)
        at println @ com.monovore.decline.effect.CommandIOApp$.addVersionFlag(CommandIOApp.scala:67)
        at ensureOr$extension @ org.apache.daffodil.debugger.dap.Compiler$$anon$1.compile(Compiler.scala:38)
        at map @ org.apache.daffodil.debugger.dap.Compiler$$anon$1.compile(Compiler.scala:39)
        at map @ org.apache.daffodil.debugger.dap.Parse$.apply(Parse.scala:80)
        at flatMap @ org.apache.daffodil.debugger.dap.Parse$.apply(Parse.scala:78)
        at println @ com.monovore.decline.effect.CommandIOApp$.addVersionFlag(CommandIOApp.scala:67)
        at map @ org.apache.daffodil.debugger.dap.Parse$Debugee$LaunchArgs$Manual.data(Parse.scala:219)
        at flatMap @ org.apache.daffodil.debugger.dap.Parse$.$anonfun$debugee$20(Parse.scala:683)
        at unsafeRunSync @ org.apache.daffodil.debugger.dap.DAPSession$Server.dispatchRequest(DAPodil.scala:86)
        at apply @ org.apache.daffodil.debugger.dap.DAPSession$.resource(DAPodil.scala:70)
        at apply @ org.apache.daffodil.debugger.dap.DAPSession$.resource(DAPodil.scala:70)
        at unsafeRunSync @ org.apache.daffodil.debugger.dap.DAPSession$Server.dispatchRequest(DAPodil.scala:86)
        at apply @ org.apache.daffodil.debugger.dap.DAPSession$.resource(DAPodil.scala:70)
2023-06-14 18:34:37,696 [io-compute-9] INFO  o.a.d.d.d.DAPSession - <R #2 launch failure null 
2023-06-14 18:34:37,699 [io-compute-5] INFO  o.a.d.d.d.DAPSession - R> #4 disconnect {"restart":false} 
2023-06-14 18:34:37,699 [io-compute-blocker-6] WARN  o.a.d.d.d.DAPodil - ignoring setBreakPoints request since previous launch failed 
2023-06-14 18:34:37,699 [io-compute-blocker-6] INFO  o.a.d.d.d.DAPSession - <R #3 setBreakpoints failure null 
2023-06-14 18:34:37,700 [io-compute-blocker-6] INFO  o.a.d.d.d.DAPSession - <R #4 disconnect success null 
2023-06-14 18:34:37,700 [io-compute-9] DEBUG o.a.d.d.d.DAPodil - whenDone: completed 
2023-06-14 18:34:37,700 [io-compute-9] DEBUG o.a.d.d.d.DAPodil - hotswap: Succeeded 
2023-06-14 18:34:37,702 [io-compute-3] INFO  o.a.d.d.d.DAPodil - disconnected at tcp://0.0.0.0:4711 
```

So would an okay fix be removing the blocking dialog error and only displaying in the terminal where the debugger was ran?

**Comment by shanedell** [comment]
@mbeckerle Is this what should happen for any debugger issue? I believe there are others currently that will have this blocking message. If this something we want to remove all together for the debugger I should be able to do that. I like having the main error inside of the terminal, then having the debugger relay to the extension that it had an error and the extension just shows a small notification in the corner saying the debugger crashed saying to look at the debugger output for more information as to why.

**Comment by mbeckerle** [comment]
Reopening.

On 1.3.0-RC3, I edited a typo into a dfdl property value.  I should get an SDE  error message in the terminal (or somewhere), but I get only a backtrace about....
```
Exception in thread "io-compute-5" java.lang.ExceptionInInitializerError
        at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:81)
        at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:179)
        at com.sun.xml.bind.v2.runtime.reflect.Accessor$FieldReflection.optimize(Accessor.java:285)
        at com.sun.xml.bind.v2.runtime.property.ArrayProperty.<init>(ArrayProperty.java:68)
        at com.sun.xml.bind.v2.runtime.property.ArrayERProperty.<init>(ArrayERProperty.java:88)
        at com.sun.xml.bind.v2.runtime.property.ArrayElementProperty.<init>(ArrayElementProperty.java:100)
        at com.sun.xml.bind.v2.runtime.property.ArrayElementNodeProperty.<init>(ArrayElementNodeProperty.java:62)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:128)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:181)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:503)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:320)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:139)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1138)
        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:162)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:262)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:249)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:456)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:656)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:599)
        at org.apache.daffodil.tdml.TDML$.generate(TDML.scala:183)
        at org.apache.daffodil.tdml.TDML$.generate(TDML.scala:151)
        at org.apache.daffodil.debugger.dap.Parse$.$anonfun$debugee$2(Parse.scala:591)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at cats.effect.IOFiber.runLoop(IOFiber.scala:283)
        at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1338)
        at cats.effect.IOFiber.run(IOFiber.scala:140)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:549)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2a48d10f
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.getMethod(Injector.java:184)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.access$000(Injector.java:69)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1.run(Injector.java:168)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1.run(Injector.java:165)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.<clinit>(Injector.java:164)
        ... 36 more
java.lang.ExceptionInInitializerError
        at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:81)
        at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:179)
        at com.sun.xml.bind.v2.runtime.reflect.Accessor$FieldReflection.optimize(Accessor.java:285)
        at com.sun.xml.bind.v2.runtime.property.ArrayProperty.<init>(ArrayProperty.java:68)
        at com.sun.xml.bind.v2.runtime.property.ArrayERProperty.<init>(ArrayERProperty.java:88)
        at com.sun.xml.bind.v2.runtime.property.ArrayElementProperty.<init>(ArrayElementProperty.java:100)
        at com.sun.xml.bind.v2.runtime.property.ArrayElementNodeProperty.<init>(ArrayElementNodeProperty.java:62)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:128)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:181)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:503)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:320)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:139)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1138)
        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:162)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:262)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:249)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:456)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:656)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:599)
        at org.apache.daffodil.tdml.TDML$.generate(TDML.scala:183)
        at org.apache.daffodil.tdml.TDML$.generate(TDML.scala:151)
        at org.apache.daffodil.debugger.dap.Parse$.$anonfun$debugee$2(Parse.scala:591)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at cats.effect.IOFiber.runLoop(IOFiber.scala:283)
        at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1338)
        at cats.effect.IOFiber.run(IOFiber.scala:140)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:549)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2a48d10f
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.getMethod(Injector.java:184)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.access$000(Injector.java:69)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1.run(Injector.java:168)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1.run(Injector.java:165)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.<clinit>(Injector.java:164)
        ... 36 more
bash-5.0$ 
```

**Comment by mbeckerle** [comment]
Is this a java 17 issue perhaps? Reflection being used somewhere that Java 17 no longer allows?

**Comment by mbeckerle** [comment]
Verified. This is Java 17 issue. (Release note needed)
Using Java 11 I do not get the backtrace, and I do see the schema definition error message in the terminal. 
```
2023-06-22 17:08:34,337 [io-compute-5] DEBUG o.a.d.d.d.DAPodil - debugee: Errored(org.apache.daffodil.debugger.dap.Compiler$CompilationFailed: Schema Definition Error: Error loading schema due to org.xml.sax.SAXParseException; lineNumber: 93; columnNumber: 32; cvc-enumeration-valid: Value 'bytes1' is not facet-valid with respect to enumeration '[bits, bytes, characters]'. It must be a value from the enumeration.
```

**Comment by mbeckerle** [comment]
Closing. Works so long as you use Java 11, not Java 17.
