### ISSUE TITLE
Nightly tests failing Jan 2024

### ISSUE THREAD

**Issue by arosien** [apache/daffodil-vscode#942]
Followup to #855, looks like windows-only [nightly tests](https://github.com/apache/daffodil-vscode/actions/workflows/nightly.yml) are failing due to [a running process having an open file handle which is attempted to be deleted](https://github.com/apache/daffodil-vscode/actions/runs/7571105899/job/20617948445):
```
 1 failing
  1) Daffodil Debugger
       "after all" hook for "should output json infoset":
     Error: EBUSY: resource busy or locked, unlink '\\?\d:\a\daffodil-vscode\daffodil-vscode\daffodil-debugger-3.5.0-1.4.0-SNAPSHOT\lib\ch.qos.logback.logback-classic-1.2.11.jar'
Error: 1 tests failed.
  	at unlinkSync (node:fs:1829:3)
	at d:\a\daffodil-vscode\daffodil-vscode\out\tests\suite\index.js:64:27
  	at _unlinkSync (node:internal/fs/rimraf:214:14)
	at done (d:\a\daffodil-vscode\daffodil-vscode\node_modules\mocha\lib\mocha.js:1012:7)
Extension host test runner error Error: 1 tests failed.
	at d:\a\daffodil-vscode\daffodil-vscode\out\tests\suite\index.js:64:27
	at done (d:\a\daffodil-vscode\daffodil-vscode\node_modules\mocha\lib\mocha.js:1012:7)
  	at rimrafSync (node:internal/fs/rimraf:195:7)
  	at node:internal/fs/rimraf:253:9
  	at Array.forEach (<anonymous>)
  	at _rmdirSync (node:internal/fs/rimraf:250:7)
  	at rimrafSync (node:internal/fs/rimraf:193:7)
  	at node:internal/fs/rimraf:253:9
  	at Array.forEach (<anonymous>)
  	at _rmdirSync (node:internal/fs/rimraf:250:7)
  	at rimrafSync (node:internal/fs/rimraf:193:7)
  	at Object.rmSync (node:fs:1278:10)
  	at d:\a\daffodil-vscode\daffodil-vscode\out\tests\suite\daffodilDebugger.test.js:107:12
  	at Generator.next (<anonymous>)
  	at fulfilled (d:\a\daffodil-vscode\daffodil-vscode\out\tests\suite\daffodilDebugger.test.js:44:58)

Asking native host service to exit with code 1.
[main 2024-01-18T14:11:16.669Z] Extension host with pid 3352 exited with code: 0, signal: unknown.
Exit code:   1
Failed to run tests: Failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by arosien** [comment]
Will check the nightly builds to see if #943 helps.

**Comment by arosien** [comment]
Ok #943 didn't work: windows builds failing like https://github.com/apache/daffodil-vscode/actions/runs/7604784231/job/20708136908 @ commit 4de2a3be:
```
 1 failing
  1) Daffodil Debugger
       "after all" hook for "should output json infoset":
     Error: EBUSY: resource busy or locked, unlink '\\?\d:\a\daffodil-vscode\daffodil-vscode\daffodil-debugger-3.5.0-1.4.0-SNAPSHOT\lib\ch.qos.logback.logback-classic-1.2.11.jar'
  	at unlinkSync (node:fs:1829:3)
  	at _unlinkSync (node:internal/fs/rimraf:214:14)
  	at rimrafSync (node:internal/fs/rimraf:195:7)
  	at node:internal/fs/rimraf:253:9
  	at Array.forEach (<anonymous>)
  	at _rmdirSync (node:internal/fs/rimraf:250:7)
  	at rimrafSync (node:internal/fs/rimraf:193:7)
  	at node:internal/fs/rimraf:253:9
  	at Array.forEach (<anonymous>)
  	at _rmdirSync (node:internal/fs/rimraf:250:7)
  	at rimrafSync (node:internal/fs/rimraf:193:7)
  	at Object.rmSync (node:fs:1278:10)
  	at d:\a\daffodil-vscode\daffodil-vscode\out\tests\suite\daffodilDebugger.test.js:107:12
  	at Generator.next (<anonymous>)
  	at fulfilled (d:\a\daffodil-vscode\daffodil-vscode\out\tests\suite\daffodilDebugger.test.js:44:58)
```

**Comment by arosien** [comment]
#946 helped reduce the number of failures, and there are no more EBUSY clean up problems on windows. https://github.com/apache/daffodil-vscode/actions/runs/7792656128 for Feb 5 only had one failure.

**Comment by arosien** [comment]
Strange XSD errors on mac:
```
[info] Compiling 1 XSD file(s) to /Users/runner/work/daffodil-vscode/daffodil-vscode/debugger/target/scala-2.12/src_managed_cxf
parsing a schema...
Error:  "file:/Users/runner/work/daffodil-vscode/daffodil-vscode/debugger/target/scala-2.12/resource_managed/xsd/org/apache/daffodil/xsd/DFDL_part3_model.xsd" is not a part of this compilation. Is this a mistake for "file:/Users/runner/work/daffodil-vscode/daffodil-vscode/debugger/target/scala-2.12/resource_managed/xsd/org/apache/daffodil/xsd/DFDL_part1_simpletypes.xsd"?
  line 26 of file:/Users/runner/work/daffodil-vscode/daffodil-vscode/debugger/src/main/resources/bindings.xjb
```

timeouts happening on windows:
```
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error Error: https://registry.yarnpkg.com/rxjs/-/rxjs-7.8.1.tgz: ESOCKETTIMEDOUT
```

The network problems might be addressed by [specifying a longer timeout](https://stackoverflow.com/questions/52135815/yarn-is-having-troubles-with-the-network-connection) during `yarn install`.

If both are transient errors then perhaps adding action retries via [retry action](https://github.com/nick-fields/retry) would help.

**Comment by hdalsania** [comment]
The nightly tests fails randomly and intermittently across different configuration of mac OS, Java, Node and VS Code. These failed tests can be resolved by re-running them manually. Failed tests are not consistent and not across any particular configuration.  As the originally reported failure has been addressed, we will close this issue.

Moving forward, if any test failures become consistent with any specific configuration, a new issue will be created for further investigation.
